name: CI/CD Demo

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: install dependencies
        run: |
          pip3 install -r requirements.txt
      
      - name: run tests
        run: |
          pytest test/test.py
      
      - name: build docker image
        run: |
          docker build -t davejfranco/python-fastapi-demo:${{ github.sha }} .
      
      - name: docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: push docker image
        run: |
          docker push davejfranco/python-fastapi-demo:${{ github.sha }}

    outputs:
      image: davejfranco/python-fastapi-demo:${{ github.sha }}
  
  cd:
    needs: ci
    runs-on: ubuntu-latest
    steps:

      - name: AWS authentication
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          role-duration-seconds: 1200
          role-session-name: ${{ github.sha }}
          aws-region: us-east-1
      
      - name: update deployment
        run: |
          aws eks update-kubeconfig --name ${{ secrets.CLUSTER_NAME }} --region us-east-1
          kubectl set image deployment/python-fastapi-deployment api=davejfranco/python-fastapi-demo:${{ needs.ci.outputs.image }} -n app
        
  